# Generated by Django 4.2.1 on 2023-12-18 10:45

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-time_create']},
        ),
        migrations.AlterModelManagers(
            name='blog',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['-time_create'], name='blog_blog_time_cr_e22e78_idx'),
        ),
    ]
